spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:dbagnos};encrypt=false
    username: ${DB_USER:sa}
    password: ${DB_PASS:YourStrongPassword123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: validate

  flyway:
    locations: classpath:db/migration/sqlserver
